import streamlit as st

from backend.chat_store import (
    add_message,
    create_session,
    delete_session,
    get_memory_summary,
    get_recent_messages,
    get_session,
    list_sessions,
)
from backend.rag_pipeline import ask_question_across_documents, list_indexed_documents, update_memory_summary_for_session

st.set_page_config(page_title="Local PDF RAG Chatbot", page_icon=":books:", layout="wide")
st.title("Local PDF RAG Chatbot")
st.caption("Use the Admin page to upload PDFs and build local FAISS indexes.")

indexed_docs = list_indexed_documents()
if not indexed_docs:
    st.warning("No indexed PDFs found. General LLM answers will be used until documents are indexed.")

doc_names = sorted({item.get("pdf_name", "") for item in indexed_docs if item.get("pdf_name", "")})
st.caption(f"Indexed documents available: {', '.join(doc_names)}")

# Sidebar: session-based conversation history like Claude/GPT
if "active_session_id" not in st.session_state:
    sessions = list_sessions()
    st.session_state.active_session_id = sessions[0]["id"] if sessions else create_session()

with st.sidebar:
    st.subheader("Conversations")
    if st.button("Start new conversation", use_container_width=True):
        st.session_state.active_session_id = create_session()
        st.rerun()

    sessions = list_sessions()
    st.markdown("---")
    for session in sessions:
        sid = session["id"]
        label = session.get("title") or "New Chat"
        if sid == st.session_state.active_session_id:
            st.markdown(f"**Current:** {label}")
        else:
            if st.button(label, key=f"session_{sid}", use_container_width=True):
                st.session_state.active_session_id = sid
                st.rerun()

    if st.session_state.active_session_id:
        if st.button("Delete current chat", type="secondary", use_container_width=True):
            current_id = st.session_state.active_session_id
            delete_session(current_id)
            remaining = list_sessions()
            st.session_state.active_session_id = remaining[0]["id"] if remaining else create_session()
            st.rerun()

session = get_session(st.session_state.active_session_id)
if not session:
    st.session_state.active_session_id = create_session()
    session = get_session(st.session_state.active_session_id)

chat_history = session.get("messages", [])
for message in chat_history:
    role = message.get("role", "assistant")
    content = message.get("content", "")
    with st.chat_message(role):
        st.markdown(content)

user_question = st.chat_input("Ask a question from any indexed PDF")
if user_question:
    prior_history = get_recent_messages(st.session_state.active_session_id, limit=12)
    memory_summary = get_memory_summary(st.session_state.active_session_id)
    add_message(st.session_state.active_session_id, "user", user_question)
    with st.chat_message("user"):
        st.markdown(user_question)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                result = ask_question_across_documents(
                    user_question,
                    k=4,
                    allow_general_fallback=True,
                    memory_summary=memory_summary,
                    chat_history=prior_history,
                )
                answer = result["answer"]
                sources = result.get("source_documents", [])
                mode = result.get("response_mode", "rag")
                if sources:
                    answer = f"{answer}\n\n**Source document(s):** {', '.join(sources)}"
                elif mode == "general":
                    answer = f"{answer}\n\n**Note:** This answer is generated by LLM general knowledge (not from indexed `source_documents`)."
            except Exception as exc:
                answer = f"Error: {exc}"
            st.markdown(answer)
            add_message(st.session_state.active_session_id, "assistant", answer)
            update_memory_summary_for_session(st.session_state.active_session_id)
